grafana:
  image: grafana/grafana:dev
  ports:
    - "3000:3000"
  volumes:
    - ./dist:/var/lib/grafana/plugins/briangann-dotdiagram-panel
    - ./provisioning:/etc/grafana/provisioning
  environment:
    - TERM=linux
    - GF_LOG_LEVEL=debug
    - GF_DATAPROXY_LOGGING=true
